### ISSUE TITLE
update crawler image to pre-install Fmask

### ISSUE THREAD

**Issue by thiagomanel** [fogbow/sebal-engine#26]
A related issue: should we keep the Fmask step in the crawler? Or should we move it to the worker node?

**Comment by fubica** [comment]
On Jun 21, 2016, at 16:44 , Thiago Emmanuel Pereira <notifications@github.com> wrote:

> A related issue: should we keep the Fmask step in the crawler? Or should we move it to the worker node?
> 
What are the pros and cons?
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

____________________________________________________________
 Francisco Vilar Brasileiro                                   VoIP:  +55 83 1075 2038
 Departamento de Sistemas e Computação   Fone:  +55 83 2101 1644
 Universidade Federal de Campina Grande   Fax:    +55 83 2101 1498
 58.429-900, Campina Grande, PB, Brasil      E-mail: fubica@dsc.ufcg.edu.br

**Comment by thiagomanel** [comment]
the pros: we reduce the crawler memory requirement from 8GB to 1GB and remove a (possible) processing bottleneck.
the con: we waste some dev hours if there is no bottleneck.

so, I think the way to go is to wait for the performance numbers before starting changing the code

**Comment by fubica** [comment]
On Jun 21, 2016, at 17:28 , Thiago Emmanuel Pereira <notifications@github.com> wrote:

> the pros: we reduce the crawler memory requirement from 8GB to 1GB and remove a (possible) processing bottleneck.
> 
I see. I wouldn't bother with this now. Moving the Fmask processing to the worker nodes will force all of them to have at least 8GB. Of course, this is not a problem now, since we are processing the whole scene, and this requires VMs with at least 16G, but if we decide in the future to slice the scene to run it in several workers in parallel to reduce the memory footprint of the workers, then this will be a problem, and we might need to send the processing of the Fmask back to the crawler.
> the con: we waste some dev hours if there is no bottleneck.
> 
> so, I think the way to go is to wait for the performance numbers before starting changing the code
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

____________________________________________________________
 Francisco Vilar Brasileiro                                   VoIP:  +55 83 1075 2038
 Departamento de Sistemas e Computação   Fone:  +55 83 2101 1644
 Universidade Federal de Campina Grande   Fax:    +55 83 2101 1498
 58.429-900, Campina Grande, PB, Brasil      E-mail: fubica@dsc.ufcg.edu.br

**Comment by EsdrasVP** [comment]
Closing old issue.
